import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen, Table2, FileText, Presentation, ChevronLeft, Plus, Trash2, Send, Trophy, CheckCircle2, Lock, X} from 'lucide-react';
import './styles.css';

const AVATARS=['🧑🏽‍💻','👩🏻‍🎓','🧑🏾‍🚀','👨🏼‍🎨','👩🏿‍🔬','🧑🏻‍🏫'];
const categories=[
 {id:'spreadsheet',name:'Planilhas eletrônicas',icon:Table2,desc:'Aprenda a organizar dados, usar fórmulas e trabalhar com tabelas.',color:'mint'},
 {id:'text',name:'Digitação e texto',icon:FileText,desc:'Pratique digitação e formatação de documentos.',color:'violet'},
 {id:'presentation',name:'Apresentações',icon:Presentation,desc:'Crie e organize apresentações de forma visual.',color:'orange'}
];
const challenges={
 spreadsheet:[
  {id:'sheet-easy',level:'Fácil',title:'Primeiros valores',desc:'Digite os valores pedidos nas células indicadas.',objective:'Preencha A1, B1 e C1.',req:['A1 deve ser 10','B1 deve ser 20','C1 deve ser 30']},
  {id:'sheet-medium',level:'Médio',title:'Total de vendas',desc:'Use uma fórmula para calcular o total.',objective:'Some as vendas de B2 até B5 em B6.',req:['B2 contém 120','B3 contém 85','B4 contém 150','B5 contém 95','B6 mostra o total 450 por fórmula']},
  {id:'sheet-hard',level:'Difícil',title:'Análise de dados',desc:'Organize os valores e calcule indicadores.',objective:'Preencha a tabela e os cálculos.',req:['Digite 100, 200 e 300','Calcule a soma: 600','Calcule a média: 200','Informe o maior valor: 300','Informe o menor valor: 100','Calcule 10% do total: 60']}
 ],
 text:[
  {id:'text-easy',level:'Fácil',title:'Digite com atenção',desc:'Pratique a digitação de uma frase.',objective:'Digite exatamente: A tecnologia aproxima pessoas.',req:['Texto corresponde ao solicitado','Possui 4 palavras','Possui pontuação final']},
  {id:'text-medium',level:'Médio',title:'Meu primeiro documento',desc:'Crie um título e um parágrafo formatados.',objective:'Use o título solicitado em negrito e centralizado.',req:['Título correto','Título em negrito','Título centralizado','Título com 24px','Parágrafo possui texto']},
  {id:'text-hard',level:'Difícil',title:'Documento organizado',desc:'Monte uma pequena página com formatação.',objective:'Inclua título, parágrafo, lista e destaques.',req:['Há um título centralizado','Há um parágrafo','Há lista com 3 itens','Existe texto em negrito','Existe texto em itálico']}
 ],
 presentation:[
  {id:'slides-easy',level:'Fácil',title:'Meu primeiro slide',desc:'Crie um slide com título e subtítulo.',objective:'Preencha os dois campos do primeiro slide.',req:['Há um título','Há um subtítulo']},
  {id:'slides-medium',level:'Médio',title:'Apresentação em dois slides',desc:'Organize uma apresentação curta.',objective:'Crie dois slides; o segundo deve ter uma lista.',req:['Há 2 slides','Slide 1 tem título','Slide 1 tem subtítulo','Slide 2 tem título','Slide 2 possui 3 itens de lista']},
  {id:'slides-hard',level:'Difícil',title:'Conte uma história',desc:'Crie uma apresentação de três slides.',objective:'Use títulos, textos, lista e elementos visuais.',req:['Há 3 slides','Todos os slides têm título','Há conteúdo em todos os slides','Há uma lista com 3 itens','Foi escolhido um tema colorido']}
 ]
};
const knowledge={
 'célula':'Uma célula é o encontro de uma coluna com uma linha em uma planilha. A1, por exemplo, fica na coluna A e linha 1.',
 'fórmula':'Uma fórmula faz um cálculo automaticamente. Ela começa com =, como =SUM(B2:B5).', hardware:'Hardware são as partes físicas do computador, como teclado, mouse e monitor.', software:'Software são os programas e sistemas que executam no computador.',
 'copiar':'Use Ctrl+C para copiar e Ctrl+V para colar. No Mac, use Command no lugar de Ctrl.', senha:'Use uma senha longa, única e não a compartilhe. Desconfie de mensagens que a pedem.', phishing:'Phishing é uma tentativa de enganar você para roubar dados, normalmente usando links ou mensagens falsas.',
 'computador':'Um computador é uma máquina que recebe dados, processa informações e apresenta resultados.', arquivo:'Um arquivo guarda uma informação, como uma foto ou documento. Uma pasta serve para organizá-los.', internet:'A internet conecta computadores e permite acessar sites e serviços.', slide:'Um slide é uma página de uma apresentação, usada para comunicar uma ideia visualmente.'
};
const storage={get:()=>{try{const saved=JSON.parse(localStorage.getItem('playground-data')||'{}');return {student:saved.student||null,attempts:Array.isArray(saved.attempts)?saved.attempts:[]}}catch{return {student:null,attempts:[]}}},save:d=>localStorage.setItem('playground-data',JSON.stringify(d))};
const levelClass=l=>l==='Fácil'?'easy':l==='Médio'?'medium':'hard';

function App(){const [data,setData]=useState(storage.get);const [page,setPage]=useState(data.student?'home':'welcome');const [category,setCategory]=useState(null);const [challenge,setChallenge]=useState(null);const [result,setResult]=useState(null);const save=next=>{setData(next);storage.save(next)};
 if(page==='welcome')return <Welcome onStart={student=>{save({...data,student});setPage('home')}}/>;
 const goChallenges=c=>{setCategory(c);setPage('challenges')};
 return <><Header student={data.student} onHome={()=>setPage('home')} onProgress={()=>setPage('progress')}/>{page==='home'&&<Home student={data.student} onSelect={goChallenges}/>} {page==='challenges'&&<ChallengeList category={category} attempts={data.attempts} onBack={()=>setPage('home')} onOpen={c=>{setChallenge(c);setPage('activity')}}/>}{page==='activity'&&<Activity challenge={challenge} onBack={()=>setPage('challenges')} onFinish={r=>{const attempts=[...data.attempts,r];save({...data,attempts});setResult(r)}}/>}{page==='progress'&&<Progress data={data} onBack={()=>setPage('home')}/>} {result&&<Result result={result} challenge={challenge} close={()=>{setResult(null);setPage('challenges')}}/>}<Instructor/></>}
function Welcome({onStart}){const [name,setName]=useState('');const [avatar,setAvatar]=useState(AVATARS[0]);return <main className="welcome"><div className="hero-mark"><BookOpen/></div><p className="eyebrow">APRENDER FAZENDO</p><h1>PLAYGROUND</h1><p>Um espaço para aprender informática praticando.</p><section className="identity"><label>Como podemos chamar você?<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome"/></label><span>Escolha seu avatar</span><div className="avatars">{AVATARS.map(a=><button aria-label={'Avatar '+a} className={avatar===a?'selected':''} onClick={()=>setAvatar(a)}>{a}</button>)}</div><button className="primary" disabled={!name.trim()} onClick={()=>onStart({id:crypto.randomUUID(),name:name.trim(),avatar})}>Começar →</button></section></main>}
function Header({student,onHome,onProgress}){return <header><button className="brand" onClick={onHome}><span>✦</span> Playground</button><nav><button onClick={onHome}>Atividades</button><button onClick={onProgress}>Meu progresso</button></nav><div className="student"><span>{student.avatar}</span><b>{student.name}</b></div></header>}
function Home({student,onSelect}){return <main className="container"><div className="intro"><div><p className="eyebrow">OLÁ, {student.name.toUpperCase()}!</p><h2>O que vamos praticar hoje?</h2><p>Escolha uma área e avance no seu ritmo.</p></div><div className="xp">⚡ <b>0 XP</b><small>Seu progresso começa aqui</small></div></div><div className="categories">{categories.map(c=>{let Icon=c.icon;return <button className={'category '+c.color} onClick={()=>onSelect(c)}><Icon/><h3>{c.name}</h3><p>{c.desc}</p><span>Explorar →</span></button>})}</div><section className="tip"><b>✦ Dica do Instrutor</b><p>Não tenha pressa: experimentar é uma das melhores maneiras de aprender informática.</p></section></main>}
function ChallengeList({category,attempts,onBack,onOpen}){return <main className="container"><button className="back" onClick={onBack}><ChevronLeft/> Categorias</button><p className="eyebrow">TRILHA DE APRENDIZAGEM</p><h2>{category.name}</h2><p>{category.desc}</p><div className="trail">{challenges[category.id].map((c,i)=>{const best=Math.max(0,...attempts.filter(a=>a.challengeId===c.id).map(a=>a.score));return <article className="challenge-card"><div className={'level '+levelClass(c.level)}>{i+1}</div><div><span className={'pill '+levelClass(c.level)}>{c.level}</span><h3>{c.title}</h3><p>{c.desc}</p><small>Objetivo: {c.objective}</small></div><aside>{best?<><CheckCircle2/> Melhor: {best}</>:<><Lock/> Não iniciado</>}<button className="secondary" onClick={()=>onOpen(c)}>{best?'Refazer':'Começar'}</button></aside></article>})}</div></main>}
function Activity({challenge,onBack,onFinish}){const started=useMemo(()=>Date.now(),[]);const finish=checks=>{let correct=checks.filter(Boolean).length;onFinish({id:crypto.randomUUID(),challengeId:challenge.id,score:Math.round(correct/checks.length*100),correct,total:checks.length,checks,startedAt:new Date(started).toISOString(),completedAt:new Date().toISOString(),durationSeconds:Math.round((Date.now()-started)/1000)})};return <main className="container activity"><button className="back" onClick={onBack}><ChevronLeft/> Voltar aos desafios</button><div className="activity-heading"><div><span className={'pill '+levelClass(challenge.level)}>{challenge.level}</span><h2>{challenge.title}</h2><p>{challenge.desc}</p></div><div className="objective"><b>Objetivo</b><p>{challenge.objective}</p></div></div>{challenge.id.startsWith('sheet')?<Spreadsheet challenge={challenge} finish={finish}/>:challenge.id.startsWith('text')?<TextEditor challenge={challenge} finish={finish}/>:<Slides challenge={challenge} finish={finish}/>}</main>}
function Spreadsheet({challenge,finish}){const [cells,setCells]=useState({});const [selected,setSelected]=useState('A1');const set=(key,v)=>setCells({...cells,[key]:v});const range=r=>{let [a,b]=r.split(':');let col=a[0],start=+a.slice(1),end=+(b||a).slice(1);return Array.from({length:end-start+1},(_,i)=>col+(start+i))};const value=k=>{const v=cells[k]||'';if(!v.startsWith('='))return Number(v)||0;const refs=(v.match(/[A-Z]\d+(?::[A-Z]\d+)?/g)||[]).flatMap(range);if(v.toUpperCase().includes('SUM'))return refs.reduce((s,x)=>s+value(x),0);if(v.toUpperCase().includes('AVERAGE'))return refs.reduce((s,x)=>s+value(x),0)/refs.length;return 0};let checks=[];if(challenge.id==='sheet-easy')checks=['A1','B1','C1'].map((x,i)=>String(cells[x])===String([10,20,30][i]));if(challenge.id==='sheet-medium')checks=['B2','B3','B4','B5'].map((x,i)=>String(cells[x])===String([120,85,150,95][i])).concat(cells.B6?.startsWith('=')&&value('B6')===450);if(challenge.id==='sheet-hard')checks=[cells.A2==100&&cells.A3==200&&cells.A4==300,value('B2')===600,value('B3')===200,value('B4')===300,value('B5')===100,value('B6')===60];return <section className="workspace"><div className="formula"><b>{selected}</b><span>fx</span><input value={cells[selected]||''} onChange={e=>set(selected,e.target.value)} placeholder="Digite um valor ou fórmula"/></div><div className="sheet"><div className="corner"/>{['A','B','C','D','E'].map(x=><b>{x}</b>)}{[1,2,3,4,5,6].flatMap(row=>[<b>{row}</b>,...['A','B','C','D','E'].map(col=>{let k=col+row;return <input aria-label={k} className={selected===k?'active':''} value={cells[k]||''} onFocus={()=>setSelected(k)} onChange={e=>set(k,e.target.value)}/>})])}</div><p className="formula-help">Você pode usar fórmulas como <code>=SUM(B2:B5)</code> ou <code>=AVERAGE(A2:A4)</code>.</p><button className="primary" onClick={()=>finish(checks)}>Verificar desafio</button></section>}
function TextEditor({challenge,finish}){const [title,setTitle]=useState('');const [body,setBody]=useState('');const [bold,setBold]=useState(false),[italic,setItalic]=useState(false),[align,setAlign]=useState('left'),[size,setSize]=useState('18');const words=body.trim()?body.trim().split(/\s+/).length:0;const check=()=>{let c=[];if(challenge.id==='text-easy')c=[body.trim()==='A tecnologia aproxima pessoas.',words===4,body.trim().endsWith('.')]; if(challenge.id==='text-medium')c=[title.trim()==='Minha Primeira Experiência com Tecnologia',bold,align==='center',Number(size)>=24,body.trim().length>0];if(challenge.id==='text-hard')c=[title.trim().length>0&&align==='center',body.trim().length>0,body.split('\n').filter(x=>x.trim().startsWith('-')).length>=3,bold,italic];finish(c)};return <section className="editor"><div className="toolbar"><button className={bold?'on':''} aria-label="Negrito" onClick={()=>setBold(!bold)}><b>B</b></button><button className={italic?'on':''} aria-label="Itálico" onClick={()=>setItalic(!italic)}><i>I</i></button><button onClick={()=>setAlign(align==='center'?'left':'center')}>☰ Alinhar</button><select aria-label="Tamanho da fonte" value={size} onChange={e=>setSize(e.target.value)}><option value="18">18 px</option><option value="24">24 px</option><option value="32">32 px</option></select></div><div className="document" style={{textAlign:align}}><input className="doc-title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Título" style={{fontSize:size+'px',fontWeight:bold?'700':'400',fontStyle:italic?'italic':'normal'}}/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Comece a escrever aqui..." style={{fontWeight:bold?'700':'400',fontStyle:italic?'italic':'normal'}}/></div><div className="editor-foot">{words} palavras · {body.length} caracteres <button className="primary" onClick={check}>Verificar desafio</button></div></section>}
function Slides({challenge,finish}){const [slides,setSlides]=useState([{title:'',content:'',theme:'blue'}]);const [current,setCurrent]=useState(0);const update=(key,val)=>setSlides(slides.map((s,i)=>i===current?{...s,[key]:val}:s));const add=()=>{setSlides([...slides,{title:'',content:'',theme:'blue'}]);setCurrent(slides.length)};const check=()=>{const list=s=>s.content.split('\n').filter(x=>x.trim().startsWith('-')).length>=3;let c=[];if(challenge.id==='slides-easy')c=[!!slides[0]?.title.trim(),!!slides[0]?.content.trim()];if(challenge.id==='slides-medium')c=[slides.length===2,!!slides[0]?.title.trim(),!!slides[0]?.content.trim(),!!slides[1]?.title.trim(),list(slides[1]||{})];if(challenge.id==='slides-hard')c=[slides.length===3,slides.every(s=>s.title.trim()),slides.every(s=>s.content.trim()),slides.some(list),slides.some(s=>s.theme!=='blue')];finish(c)};const s=slides[current];return <section className="slides"><aside className="slide-nav">{slides.map((x,i)=><button className={current===i?'thumb selected-thumb':'thumb'} onClick={()=>setCurrent(i)}><small>SLIDE {i+1}</small><b>{x.title||'Sem título'}</b></button>)}<button className="add-slide" onClick={add}><Plus/> Novo slide</button></aside><div className="slide-area"><div className={'slide '+s.theme}><input value={s.title} onChange={e=>update('title',e.target.value)} placeholder="Clique para adicionar um título"/><textarea value={s.content} onChange={e=>update('content',e.target.value)} placeholder="Clique para adicionar texto ou uma lista&#10;- Item 1"/></div><div className="slide-controls"><label>Tema <select value={s.theme} onChange={e=>update('theme',e.target.value)}><option value="blue">Azul</option><option value="purple">Roxo</option><option value="sun">Sol</option></select></label>{slides.length>1&&<button onClick={()=>{setSlides(slides.filter((_,i)=>i!==current));setCurrent(0)}}><Trash2/> Remover</button>}<button className="primary" onClick={check}>Verificar desafio</button></div></div></section>}
function Result({result,challenge,close}){const time=`${String(Math.floor(result.durationSeconds/60)).padStart(2,'0')}:${String(result.durationSeconds%60).padStart(2,'0')}`;return <div className="modal-bg" role="dialog" aria-modal="true"><div className="result"><button className="modal-close" onClick={close}><X/></button><Trophy/><p className="eyebrow">DESAFIO CONCLUÍDO!</p><h2>{result.score}/100</h2><p>Pontuação proporcional aos requisitos concluídos.</p><div className="result-stats"><b>{result.correct}/{result.total}<small>acertos</small></b><b>{time}<small>tempo</small></b></div><ul>{challenge.req.map((r,i)=><li className={result.checks[i]?'yes':'no'}>{result.checks[i]?'✓':'×'} {r}</li>)}</ul><p className="retry">Você pode tentar novamente para melhorar sua pontuação.</p><button className="primary" onClick={close}>Voltar à trilha</button></div></div>}
function Progress({data,onBack}){const best=id=>Math.max(0,...data.attempts.filter(a=>a.challengeId===id).map(a=>a.score));const rows=categories.map(c=>{let cs=challenges[c.id],scores=cs.map(x=>best(x.id));return {...c,score:Math.round(scores.reduce((a,b)=>a+b,0)/3),done:scores.filter(Boolean).length}});const all=rows.reduce((a,x)=>a+x.score,0)/3;return <main className="container"><button className="back" onClick={onBack}><ChevronLeft/> Atividades</button><div className="profile"><span>{data.student.avatar}</span><div><p className="eyebrow">MEU PROGRESSO</p><h2>{data.student.name}</h2><p>{data.attempts.length} tentativa(s) registrada(s) · melhores resultados preservados</p></div><div className="overall"><b>{Math.round(all)}%</b><small>progresso geral</small></div></div><div className="progress-grid">{rows.map(r=>{let Icon=r.icon;return <article><Icon/><h3>{r.name}</h3><div className="bar"><i style={{width:r.score+'%'}}/></div><b>{r.score}%</b><p>{r.done}/3 desafios concluídos</p></article>})}</div><section className="achievements"><h3>Conquistas</h3><div><span className={data.attempts.length?'earned':''}>🏆 Primeiro desafio</span><span className={rows[0].done?'earned':''}>📊 Explorador das planilhas</span><span className={rows[1].done?'earned':''}>⌨️ Mestre da digitação</span><span className={rows[2].done?'earned':''}>🎞️ Criador de apresentações</span></div></section></main>}
function Instructor(){const [open,setOpen]=useState(false),[q,setQ]=useState(''),[answer,setAnswer]=useState('Olá! Sou o Instrutor. Posso ajudar você com conceitos de informática básica.');const ask=x=>{setQ(x);let term=Object.keys(knowledge).find(k=>x.toLowerCase().includes(k));setAnswer(term?knowledge[term]:'Ainda estou aprendendo essa resposta. Tente perguntar sobre hardware, arquivos, fórmulas, células ou copiar e colar.')} ;return <><button className="instructor-btn" aria-label="Abrir Instrutor virtual" onClick={()=>setOpen(!open)}>🧑🏽‍🏫</button>{open&&<section className="instructor"><header><b>Instrutor virtual</b><button onClick={()=>setOpen(false)}><X/></button></header><p>{answer}</p><div className="suggestions"><button onClick={()=>ask('O que é uma fórmula?')}>💡 O que é uma fórmula?</button><button onClick={()=>ask('O que é hardware?')}>💡 O que é hardware?</button><button onClick={()=>ask('Como copiar e colar?')}>💡 Como copiar e colar?</button></div><form onSubmit={e=>{e.preventDefault();ask(q)}}><input aria-label="Pergunte ao Instrutor" value={q} onChange={e=>setQ(e.target.value)} placeholder="Digite sua dúvida..."/><button aria-label="Enviar"><Send/></button></form></section>}</>}
class ErrorBoundary extends React.Component{constructor(p){super(p);this.state={error:false}}static getDerivedStateFromError(){return {error:true}}render(){return this.state.error?<main className="welcome"><div className="identity"><h2>Não foi possível carregar o Playground.</h2><p>Apague os dados do site no navegador e atualize a página. Se o problema continuar, abra o projeto pelo comando <code>npm run dev</code>.</p></div></main>:this.props.children}}
createRoot(document.getElementById('root')).render(<ErrorBoundary><App/></ErrorBoundary>);
